variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test
  - release

.check:
  stage: test
  image: cr.yandex/crppmgcujiph4hvf0dup/hse-cxx-build:latest
  allow_failure: true
  script:
    - cmake --version
    - mkdir -p build/solutions
    - cd build/solutions
    - cmake ../../ -G Ninja -DTEST_SOLUTION=ON -DENABLE_PRIVATE_TESTS=ON
    - ninja test-all

check-solutions-clang-14:
  extends: .check
  variables:
    CC: clang-14
    CXX: clang++-14

deploy:
  only:
  - main
  tags:
  - docker
  stage: release
  script:
  - docker pull cr.yandex/crppmgcujiph4hvf0dup/hse-cxx-build:latest
  - docker build -f testenv.docker -t cr.yandex/crppmgcujiph4hvf0dup/hse-cxx-base-testenv .
  - docker push cr.yandex/crppmgcujiph4hvf0dup/hse-cxx-base-testenv
